### ISSUE TITLE
Out of fixed registers error during installation

### ISSUE THREAD

**Issue by luminousmen** [gonum/plot#311]
When I run ```go get github.com/gonum/plot/``` I got this error:
```
# bitbucket.org/zombiezen/gopdf/pdf
run compiler with -v for register allocation sites
.go/src/bitbucket.org/zombiezen/gopdf/pdf/image.go:89: internal compiler error: out of fixed registers
# rsc.io/pdf
run compiler with -v for register allocation sites
.go/src/rsc.io/pdf/page.go:250: internal compiler error: out of fixed registers
```

**Comment by sbinet** [comment]
interesting...
could you tell us the output of:

```
$> go env
$> go version
```

**Comment by luminousmen** [comment]
go env:
```GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kir/.go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_386"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"```
go version:
```go version go1.5.1 linux/386
```

**Comment by vladimir-ch** [comment]
https://github.com/golang/go/issues/12840

**Comment by kortschak** [comment]
I don't think this is us (it says it's a compiler error) - and we are not even the package that is causing it (it's happening in zombiezen and rsc's pdf package). Finally, it's not a current go version. I would try to replicate this with 1.7 and then if it persists, file an issue at golang.org/issues.

**Comment by luminousmen** [comment]
go version:
```
go version go1.7 linux/386
```
go get github.com/gonum/plot/:

```
# bitbucket.org/zombiezen/gopdf/pdf
run compiler with -v for register allocation sites
.go/src/bitbucket.org/zombiezen/gopdf/pdf/image.go:89: internal compiler error: out of fixed registers

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
cmd/compile/internal/gc.Fatalf(0x8570a2a, 0x16, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:165 +0x216
cmd/compile/internal/gc.Regalloc(0x193b9e00, 0x18a12b80, 0x193b9d40)
	/usr/local/go/src/cmd/compile/internal/gc/gsubr.go:749 +0x3a1
cmd/compile/internal/x86.ginscmp(0x8558b3e, 0x18a12b80, 0x193b9c80, 0x193b9d40, 0x1, 0x1)
	/usr/local/go/src/cmd/compile/internal/x86/gsubr.go:657 +0x3a4
cmd/compile/internal/gc.Agenr(0x18cc8900, 0x193b9800, 0x193b9680)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:1245 +0x2489
cmd/compile/internal/gc.Igen(0x18cc8900, 0x193b9800, 0x193b9680)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:1718 +0x25a
cmd/compile/internal/gc.cgen_wb(0x18cc8900, 0x193b9680, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:523 +0x3ad4
cmd/compile/internal/gc.Cgen(0x18cc8900, 0x193b9680)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:19 +0x2e
cmd/compile/internal/gc.Mgen(0x18cc8900, 0x193b9680, 0x193b95c0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:906 +0xd9
cmd/compile/internal/gc.cgen_wb(0x18cc8a20, 0x193b95c0, 0x3000)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:460 +0x3318
cmd/compile/internal/gc.Cgen(0x18cc8a20, 0x193b95c0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:19 +0x2e
cmd/compile/internal/gc.Mgen(0x18cc8a20, 0x193b95c0, 0x193b94a0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:906 +0xd9
cmd/compile/internal/gc.cgen_wb(0x18cc8c60, 0x193b94a0, 0x193b9400)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:714 +0x2067
cmd/compile/internal/gc.Cgen(0x18cc8c60, 0x193b94a0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:19 +0x2e
cmd/compile/internal/gc.cgen_wb(0x18cc8d20, 0x193b9320, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:664 +0x4257
cmd/compile/internal/gc.Cgen(0x18cc8d20, 0x193b9320)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:19 +0x2e
cmd/compile/internal/gc.Mgen(0x18cc8d20, 0x193b9320, 0x193b92c0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:906 +0xd9
cmd/compile/internal/gc.cgen_wb(0x18cc8e40, 0x193b92c0, 0x193b9200)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:460 +0x3318
cmd/compile/internal/gc.Cgen(0x18cc8e40, 0x193b92c0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:19 +0x2e
cmd/compile/internal/gc.cgen_wb(0x18cc8e40, 0x1939b080, 0x19070e00)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:102 +0x5ad
cmd/compile/internal/gc.Cgen_as_wb(0x1939b080, 0x18cc8e40, 0x200)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:1023 +0x138
cmd/compile/internal/gc.Cgen_as(0x1939b080, 0x18cc8e40)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:979 +0x2e
cmd/compile/internal/gc.gen(0x18cc9020)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:926 +0x1be
cmd/compile/internal/gc.Genlist(0x19384f90)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x18cd1e60)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:875 +0xb89
cmd/compile/internal/gc.Genlist(0x19384fb0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x18cd12c0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:860 +0x977
cmd/compile/internal/gc.Genlist(0x19384fd0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.genlegacy(0x18ad0180, 0x1938f8c0, 0x1938f940)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:498 +0x56
cmd/compile/internal/gc.compile(0x18d10060)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:485 +0xfcd
cmd/compile/internal/gc.funccompile(0x18d10060)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x167
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/main.go:467 +0x1bf4
cmd/compile/internal/x86.Main()
	/usr/local/go/src/cmd/compile/internal/x86/galign.go:80 +0x2dc
main.main()
	/usr/local/go/src/cmd/compile/main.go:31 +0x117

# rsc.io/pdf
run compiler with -v for register allocation sites
.go/src/rsc.io/pdf/page.go:250: internal compiler error: out of fixed registers

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
cmd/compile/internal/gc.Fatalf(0x8570a2a, 0x16, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:165 +0x216
cmd/compile/internal/gc.Regalloc(0x18d6e900, 0x18a12b80, 0x18d6e7e0)
	/usr/local/go/src/cmd/compile/internal/gc/gsubr.go:749 +0x3a1
cmd/compile/internal/x86.ginscmp(0x8558b3e, 0x18a12b80, 0x18d6e6c0, 0x18d6e7e0, 0x1, 0x18aeb374)
	/usr/local/go/src/cmd/compile/internal/x86/gsubr.go:657 +0x3a4
cmd/compile/internal/gc.Agenr(0x190190e0, 0x18d74fc0, 0x18d74480)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:1245 +0x2489
cmd/compile/internal/gc.Igen(0x190190e0, 0x18d74fc0, 0x18d74480)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:1718 +0x25a
cmd/compile/internal/gc.cgen_wb(0x190190e0, 0x18d74480, 0x18d74400)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:523 +0x3ad4
cmd/compile/internal/gc.Cgen(0x190190e0, 0x18d74480)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:19 +0x2e
cmd/compile/internal/gc.cgen_wb(0x190193e0, 0x18d7a2a0, 0x18d7a200)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:741 +0x254e
cmd/compile/internal/gc.Cgen(0x190193e0, 0x18d7a2a0)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:19 +0x2e
cmd/compile/internal/gc.cgen_wb(0x18e3fe60, 0x18d7d500, 0x18d7d500)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:725 +0x225c
cmd/compile/internal/gc.Cgen(0x18e3fe60, 0x18d7d500)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:19 +0x2e
cmd/compile/internal/gc.cgen_wb(0x18e3fe60, 0x18e3f860, 0x8560300)
	/usr/local/go/src/cmd/compile/internal/gc/cgen.go:102 +0x5ad
cmd/compile/internal/gc.Cgen_as_wb(0x18e3f860, 0x18e3fe60, 0x1300)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:1023 +0x138
cmd/compile/internal/gc.Cgen_as(0x18e3f860, 0x18e3fe60)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:979 +0x2e
cmd/compile/internal/gc.gen(0x19019440)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:926 +0x1be
cmd/compile/internal/gc.Genlist(0x1985c4b0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x19018a80)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:875 +0xb89
cmd/compile/internal/gc.Genlist(0x1985c4e0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x190186c0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:875 +0xb89
cmd/compile/internal/gc.Genlist(0x1985c570)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x19018480)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:875 +0xb89
cmd/compile/internal/gc.Genlist(0x1985c800)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x19015f80)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:860 +0x977
cmd/compile/internal/gc.Genlist(0x1985c5b0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x19015b60)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:875 +0xb89
cmd/compile/internal/gc.Genlist(0x1985c6e0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x19015620)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:860 +0x977
cmd/compile/internal/gc.Genlist(0x1985c5e0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x190153e0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:860 +0x977
cmd/compile/internal/gc.Genlist(0x1985c620)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.gen(0x19014ea0)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:860 +0x977
cmd/compile/internal/gc.Genlist(0x1985c630)
	/usr/local/go/src/cmd/compile/internal/gc/gen.go:311 +0x6d
cmd/compile/internal/gc.genlegacy(0x18ad2180, 0x19612bc0, 0x19612c40)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:498 +0x56
cmd/compile/internal/gc.compile(0x19014660)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:485 +0xfcd
cmd/compile/internal/gc.funccompile(0x19014660)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x167
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/main.go:467 +0x1bf4
cmd/compile/internal/x86.Main()
	/usr/local/go/src/cmd/compile/internal/x86/galign.go:80 +0x2dc
main.main()
	/usr/local/go/src/cmd/compile/main.go:31 +0x117
```

**Comment by vladimir-ch** [comment]
If I interpret it correctly, the golang issue I linked to above says that
the compiler bug on 386 won't be fixed until go 1.8.
