### ISSUE TITLE
program stops when saving an svg plot

### ISSUE THREAD

**Issue by chmike** [gonum/plot#514]
### What are you trying to do?
Save a simple svg plot with 2 points and 2 lines. The program hangs.

### What did you do?
Every day I generate ~80 svg plots, and attach them to a mail that I send to myself.

### What did you expect to happen?
As usual, get the mail with the graphs. 

### What actually happened?
Didn't receive the mail this morning. Investigated, and saw that the program blocked when saving one particular graph which has only two points, and 2 lines. The problem occurs only with that particular graph. If I skip that graph, no problem. If I try to save only this particular graph, the program blocks. 

By using the debugger, to execute the Draw function step by step, the program stops when executing 
```Go 
marks := a.Tick.Marker.Ticks(a.Min, a.Max)        // in file `axis.go` at line 296
```
with `a.Min = 99.99999999999996` and `a.Max = 100`. 

The debugger never manages to step into that function. I have no idea why. 
This is for the Y axis. It uses the default ticks and legend. 

The plot has only two points, and two horizontal lines which have the following values:

```
Points: [{X:1.5486336e+09 Y:0.77} {X:1.54872e+09 Y:0.77}]
Line1: [{X:1.5486336e+09 Y:0.77} {X:1.54872e+09 Y:0.77}]
Line2: [{X:1.5486336e+09 Y:0.7699999999999998} {X:1.5486768e+09 Y:0.7699999999999998} {X:1.54872e+09 Y:0.7699999999999998}]
```
Before passing the values to Plot, I normalize the Y values by multiplying them by (100/0.77) which yields 100. Could the different, but very close, values be the cause of the problem ? 

### What version of Go and Gonum/plot are you using?
Go1.11.4

### Does this issue reproduce with the current master?
Yes.

**Comment by sbinet** [comment]
could you show us a simple reproducer program?
thanks.

**Comment by sbinet** [comment]
> Could the different, but very close, values be the cause of the problem ?

(and, yes, I think that's the culprit)

**Comment by chmike** [comment]
Here is the most simple program producing the problem. 

``` Go
package main

import (
	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
	"gonum.org/v1/plot/vg"
)

func main() {
	p, err := plot.New()
	if err != nil {
		panic(err)
	}
	//p.Title.Text = "Test plot"
	points, err := plotter.NewScatter(plotter.XYs{{X: 1.5486336e+09, Y: 99.99999999999996}, {X: 1.54872e+09, Y: 100}})
	if err != nil {
		panic(err)
	}
	p.Add(points)
	if err := p.Save(8*vg.Inch, 3*vg.Inch, "test.svg"); err != nil {
		panic(err)
	}
}
```

**Comment by sbinet** [comment]
this works too:

```diff
diff --git a/axis.go b/axis.go
index a7ee213..0f0e143 100644
--- a/axis.go
+++ b/axis.go
@@ -6,6 +6,7 @@ package plot
 
 import (
        "image/color"
+       "log"
        "math"
        "strconv"
        "time"
@@ -293,6 +294,23 @@ func (a verticalAxis) size() (w vg.Length) {
                w += a.Label.Height(a.Label.Text)
        }
 
+       log.Printf("vert.size: min=%v max=%v", a.Min, a.Max)
+       aa := a.Min
+       for i := 0; i < 100; i++ {
+               log.Printf("next[%d]: %v -> %v", i, aa, math.Nextafter(aa, a.Max))
+               aa = math.Nextafter(aa, a.Max)
+               if aa >= a.Max {
+                       log.Printf("break!")
+                       break
+               }
+       }
+       {
+               min := math.Float64bits(a.Min)
+               max := math.Float64bits(a.Max)
+               log.Printf("min-bits=%d 0x%x", min, min)
+               log.Printf("max-bits=%d 0x%x", max, max)
+               log.Printf("==> %d", max-min)
+       }
diff --git a/plot_test.go b/plot_test.go
index 391065b..6491211 100644
--- a/plot_test.go
+++ b/plot_test.go
@@ -8,6 +8,9 @@ import (
        "bytes"
        "fmt"
        "image/color"
+       "io/ioutil"
+       "os"
+       "path/filepath"
        "reflect"
        "testing"
 
@@ -229,3 +232,31 @@ func printFirstDiff(got, want []recorder.Action) string {
        }
        return buf.String()
 }
+
+func TestIssue514(t *testing.T) {
+       p, err := plot.New()
+       if err != nil {
+               t.Fatalf("could not create plot: %v", err)
+       }
+
+       pts, err := plotter.NewScatter(plotter.XYs{
+               {X: 1, Y: 99.99999999999996},
+               {X: 1, Y: 100},
+       })
+       if err != nil {
+               t.Fatalf("could not create scatter: %v", err)
+       }
+
+       p.Add(pts)
+
+       dir, err := ioutil.TempDir("", "gonum-plot-")
+       if err != nil {
+               t.Fatalf("could not create temporary directory: %v", err)
+       }
+       defer os.RemoveAll(dir)
+
+       fname := filepath.Join(dir, "issue514.svg")
+       if err := p.Save(5*vg.Centimeter, 5*vg.Centimeter, fname); err != nil {
+               t.Fatalf("could not save scatter plot: %v", err)
+       }
+}
```
and "dies" there (in `talbotLinHanrahan` -> `simplicity`):
```
[15:09 binet@clrinfopc42 plot]$ go test -v -run=Issue
=== RUN   TestIssue514
2019/01/30 15:09:33 vert.size: min=99.99999999999996 max=100
2019/01/30 15:09:33 next[0]: 99.99999999999996 -> 99.99999999999997
2019/01/30 15:09:33 next[1]: 99.99999999999997 -> 99.99999999999999
2019/01/30 15:09:33 next[2]: 99.99999999999999 -> 100
2019/01/30 15:09:33 break!
2019/01/30 15:09:33 min-bits=4636737291354636285 0x4058fffffffffffd
2019/01/30 15:09:33 max-bits=4636737291354636288 0x4059000000000000
2019/01/30 15:09:33 ==> 3
^\SIGQUIT: quit
PC=0x49082f m=0 sigcode=128

goroutine 6 [running]:
math.ldexp(0x3d06849b86a12b9b, 0x3, 0xffffffffffffffd6)
	/home/binet/sdk/go/src/math/ldexp.go:43 +0x10f fp=0xc00012ceb8 sp=0xc00012ceb0 pc=0x49082f
math.mod(0x4058fffffffffffd, 0x3d06849b86a12b9b, 0x4058fffffffffffd)
	/home/binet/sdk/go/src/math/mod.go:44 +0x11e fp=0xc00012cef8 sp=0xc00012ceb8 pc=0x4909ee
gonum.org/v1/plot.simplicity(0x3ff0000000000000, 0xc00012d070, 0x6, 0x6, 0x1, 0x4058fffffffffffd, 0x4058ffffffffffff, 0x3d06849b86a12b9b, 0x0)
	/home/binet/work/gonum/src/gonum.org/v1/plot/labelling.go:196 +0x6f fp=0xc00012cf28 sp=0xc00012cef8 pc=0x6b53ef
gonum.org/v1/plot.talbotLinHanrahan(0x4058fffffffffffd, 0x4059000000000000, 0x3, 0x2, 0x0, 0x6, 0x6, 0x0, 0x797678, 0xc00012d200, ...)
	/home/binet/work/gonum/src/gonum.org/v1/plot/labelling.go:144 +0x1d9 fp=0xc00012d108 sp=0xc00012cf28 pc=0x6b44c9
gonum.org/v1/plot.DefaultTicks.Ticks(0x4058fffffffffffd, 0x4059000000000000, 0x0, 0x0, 0x5)
	/home/binet/work/gonum/src/gonum.org/v1/plot/axis.go:403 +0x86 fp=0xc00012d220 sp=0xc00012d108 pc=0x6b38a6
gonum.org/v1/plot.(*DefaultTicks).Ticks(0xc61e60, 0x4058fffffffffffd, 0x4059000000000000, 0x1, 0x1, 0x762e40)
	<autogenerated>:1 +0x4a fp=0xc00012d258 sp=0xc00012d220 pc=0x6be1ca
gonum.org/v1/plot.verticalAxis.size(0x4058fffffffffffd, 0x4059000000000000, 0x0, 0x0, 0x7dec40, 0xc62a00, 0x4028000000000000, 0x77974f, 0xb, 0xc000256000, ...)
	/home/binet/work/gonum/src/gonum.org/v1/plot/axis.go:314 +0x513 fp=0xc00012d4f0 sp=0xc00012d258 pc=0x6b2a63
gonum.org/v1/plot.(*Plot).Draw(0xc00010c800, 0x7e3420, 0xc000092320, 0x0, 0x0, 0x4061b76eddbb76ee, 0x4061b76eddbb76ee)
	/home/binet/work/gonum/src/gonum.org/v1/plot/plot.go:157 +0x138 fp=0xc00012ddc0 sp=0xc00012d4f0 pc=0x6b6eb8
gonum.org/v1/plot.(*Plot).WriterTo(0xc00010c800, 0x4061b76eddbb76ee, 0x4061b76eddbb76ee, 0xc000018413, 0x3, 0xc00012df78, 0x2, 0x2, 0xc0000183f0)
	/home/binet/work/gonum/src/gonum.org/v1/plot/plot.go:445 +0x138 fp=0xc00012de50 sp=0xc00012ddc0 pc=0x6b9ee8
gonum.org/v1/plot.(*Plot).Save(0xc00010c800, 0x4061b76eddbb76ee, 0x4061b76eddbb76ee, 0xc0000183f0, 0x26, 0x0, 0x0)
	/home/binet/work/gonum/src/gonum.org/v1/plot/plot.go:471 +0x130 fp=0xc00012deb0 sp=0xc00012de50 pc=0x6ba080
gonum.org/v1/plot_test.TestIssue514(0xc0000bc200)
	/home/binet/work/gonum/src/gonum.org/v1/plot/plot_test.go:259 +0x359 fp=0xc00012dfa8 sp=0xc00012deb0 pc=0x6c9c49
testing.tRunner(0xc0000bc200, 0x797740)
	/home/binet/sdk/go/src/testing/testing.go:827 +0xbf fp=0xc00012dfd0 sp=0xc00012dfa8 pc=0x4ee42f
runtime.goexit()
	/home/binet/sdk/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00012dfd8 sp=0xc00012dfd0 pc=0x45adc1
created by testing.(*T).Run
	/home/binet/sdk/go/src/testing/testing.go:878 +0x35c

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000bc200, 0x77aa67, 0xc, 0x797740, 0x47a501)
	/home/binet/sdk/go/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc0000bc100)
	/home/binet/sdk/go/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc0000bc100, 0xc000053e08)
	/home/binet/sdk/go/src/testing/testing.go:827 +0xbf
testing.runTests(0xc00000a300, 0xc403a0, 0x8, 0x8, 0x40b95f)
	/home/binet/sdk/go/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc0000a0200, 0x0)
	/home/binet/sdk/go/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:58 +0x13d

goroutine 5 [chan send]:
github.com/jung-kurt/gofpdf.glob..func1.1(0xc00006e180)
	/home/binet/work/gonum/src/github.com/jung-kurt/gofpdf/template.go:91 +0x44
created by github.com/jung-kurt/gofpdf.glob..func1
	/home/binet/work/gonum/src/github.com/jung-kurt/gofpdf/template.go:88 +0x58

rax    0x3
rbx    0xffffffffffffffd4
rcx    0x3d0
rdx    0x3d06849b86a12b9b
rdi    0x9f2860
rsi    0x2
rbp    0xc00012cee8
rsp    0xc00012ceb0
r8     0x9f4e00
r9     0x4058fffffffffffd
r10    0x4
r11    0x212
r12    0x62
r13    0x61
r14    0x200
r15    0xaa
rip    0x49082f
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
exit status 2
FAIL	gonum.org/v1/plot	1.504s
```

@kortschak will now more about that...
(I thought it was an issue with not enough ULPs between `a.Min` and `a.Max` but... nope.)

**Comment by sbinet** [comment]
actually, I take it back.
when the axis range is exactly 1 ulp, `talbotLinHanrahan` works.
but when it's in the range [2,7), it doesn't anymore.

see #515.

**Comment by chmike** [comment]
I could test the following code without problem. The error could in a loop in plot calling `math.mod` repeatedly. It might just be a coincidence that it stopped in `math.mod`. 

```Go 
println(math.Float64frombits(0x4058fffffffffffd))
println(math.Float64frombits(0x3d06849b86a12b9b))
println(math.Mod(100., 1.000000e-014))
println(math.Mod(math.Float64frombits(0x4058fffffffffffd),math.Float64frombits(0x3d06849b86a12b9b)))
println(math.Mod(math.Float64frombits(0x3d06849b86a12b9b), math.Float64frombits(0x4058fffffffffffd)))
```
